### ISSUE TITLE
Laser Scan Points Order

### ISSUE THREAD

**Issue by mfaessle** [JohsBL/flappy_automation_test#1]
I noticed that the points in the published laser scan message are ordered from angle_max to angle_min whereas they should be ordered vice versa to comply with the convention of the sensor_msgs/LaserScan message: http://docs.ros.org/api/sensor_msgs/html/msg/LaserScan.html

I think it would make sense to change this such that other ros tools (such as displaying the laser scan in rviz) can be used as well without any hacks.

**Comment by JohsBL** [comment]
Thank you for reporting the issue! Just changed the order of the laser scan message.

**Comment by mfaessle** [comment]
Thanks for fixing this. To be super consistent you would also need to adapt the line where you print a measurement in the laserScanCallback functions of both flappy_automation_code_node.py and flappy_automation_code.cpp since now the first measurement in the array does not correspond to the max_angle any longer.

**Comment by JohsBL** [comment]
Fixed the py and cpp templates to have angle_min instead of angle_max.
