### ISSUE TITLE
Velocity scaling bug

### ISSUE THREAD

**Issue by mfaessle** [JohsBL/flappy_automation_test#2]
Hey

There is a bug in this line: https://github.com/JohsBL/flappy_automation_test/blob/master/flappy_main_game/scripts/flappy.py#L293

The "*FPS" should not be there. "pipeVelX" and "playerVelY" are velocities in pixels per second and only need to be spatially scaled. (A few lines above the FPS scaling goes correctly into the integration of the accelerations.)

Cheers

**Comment by mfaessle** [comment]
It seems what I wrote here is not the whole story (or I'm just super confused now), but something seems to be off. E.g. if you send an acceleration command once the published velocity jumps to that value directly but it should be 30 times smaller. This is explainable with the FPS scaling but still not convinced that this fixes everything

**Comment by mfaessle** [comment]
OK, looking at at a bit more I think I found what could be the issue. The game itself is updated with a velocity that is in pixel per timestep and for the ros related part we treat it as if it was a velocity in pixel per second. So when we integrate the received acceleration from ros we consider the frame rate "FPS" but it is not considered when updating the game.

**Comment by mfaessle** [comment]
@JohsBL  OK I think I got it. Looking at the units of all variables the two lines integrating the acceleration commands: https://github.com/JohsBL/flappy_automation_test/blob/master/flappy_main_game/scripts/flappy.py#L285 should actually be playerAccX/FPS/FPS and playerAccY/FPS/FPS then at least for me everything makes sense and seems consistent.
Sorry for the many comments ;)

**Comment by JohsBL** [comment]
Yes, you are right. I do not convert the acceleration in: https://github.com/JohsBL/flappy_automation_test/blob/7378ac69b0b35ea28bc2d0d120f557df7ed4aa49/flappy_main_game/scripts/flappy.py#L576-L577

It should be solved by changing the lines to:
playerAccX = limitAcceleration(-data.x/SCALING,ACCXLIMIT) / (FPS * FPS)
playerAccY = limitAcceleration(-data.y/SCALING,ACCYLIMIT) / (FPS * FPS)

And removing the FPS division in: https://github.com/JohsBL/flappy_automation_test/blob/7378ac69b0b35ea28bc2d0d120f557df7ed4aa49/flappy_main_game/scripts/flappy.py#L285-L286

Will do this now.

Just saw the comment after I posted

**Comment by JohsBL** [comment]
Just pushed the changes. It should be solved now. Thanks again!

**Comment by JohsBL** [comment]
Will change the acceleration limit accordingly

**Comment by JohsBL** [comment]
Changed the acceleration limits to: 
Max acceleration x: 3.0 m/s^2
Max acceleration y: 35.0 m/s^2
